[versions]
android-gradle-plugin = "8.0.2"
androidx-annotation = "1.3.0"
androidx-appcompat = "1.4.1"
androidx-constraintlayout = "2.1.3"
androidx-core = "1.7.0"
androidx-lifecycle-extensions = "2.2.0"
androidx-lifecycle-livedata = "2.3.1"
androidx-lifecycle-runtime = "2.3.1"
androidx-lifecycle-viewmodel = "2.3.1"
androidx-localbroadcastmanager = "1.1.0"
androidx-navigation = "2.3.5"
androidx-test-junit = "1.1.2"
androidx-test-monitor = "1.4.0"
androidx-test-runner = "1.4.0"
androidx-work = "2.7.1"
desugar-jdk-libs = "1.1.5"
google-material = "1.5.0-rc01"
google-playCore-ktx = "1.8.1"
junit = "4.13.2"
kotlin = "1.6.10"
kotlinx-coroutinesTest = "1.6.0"
kotlinx-serialization = "1.3.2"
materialdaypicker = "0.7.4"
robolectric = "4.9.2"
sonarqube = "4.0.0.2929"
yahooFinance = "3.17.0"

[libraries]
androidxAnnotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidxAppcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidxLocalbroadcastmanager = { module = "androidx.localbroadcastmanager:localbroadcastmanager", version.ref = "androidx-localbroadcastmanager" }
androidxConstraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidxCore = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidxLifecycleExtensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "androidx-lifecycle-extensions" }
androidxLifecycleLivedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle-livedata" }
androidxLifecycleRuntime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle-runtime" }
androidxLifecycleViewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle-viewmodel" }
androidxNavigationFragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidxNavigationUi = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }
androidxTestJunit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-junit" }
androidxTestMonitor = { module = "androidx.test:monitor", version.ref = "androidx-test-monitor" }
androidxTestRunner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
androidxWorkRuntime = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }
androidxWorkTesting = { module = "androidx.work:work-testing", version.ref = "androidx-work" }
desugarJdkLibs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar-jdk-libs" }
googleMaterial = { module = "com.google.android.material:material", version.ref = "google-material" }
googlePlayCore = { module = "com.google.android.play:core-ktx", version.ref = "google-playCore-ktx" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinxCoroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutinesTest" }
kotlinxSerializationCore = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
materialdaypicker = { module = "ca.antonious:materialdaypicker", version.ref = "materialdaypicker" }
pluginAndroidGradle = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin" }
pluginKotlinGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
yahooFinance = { module = "com.yahoofinance-api:YahooFinanceAPI", version.ref = "yahooFinance" }

[plugins]
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
